#!/bin/bash

# Boolean class
True=0
False=1
Boolean() {
   return $1
}

# Exit behavior
OnExit() {
   Echo "Exiting program"
}
trap "OnExit; exit" SIGHUP SIGINT SIGTERM

# Output class
EchoPrefix="gitmerge:"
EchoPrefixCurrent=$EchoPrefix
Echo() {
   EchoHasFlags=$True
   EchoFlags=""
   while Boolean $EchoHasFlags; do
      if [[ $1 == "-n" || $1 == "-e" || $1 == "-E" ]]; then
         EchoFlags+="$1 "
         shift
      else
         EchoHasFlags=$False
      fi
   done
   echo $EchoFlags "$EchoPrefixCurrent $@"
   if echo "${EchoFlags//-/\-}" | grep -q "\-n"; then
      EchoPrefixCurrent=""
   else
      EchoPrefixCurrent=$EchoPrefix
   fi
}

# Program start
Echo "GITMERGE - Git repository merging utility"
